# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install build-essential python-dev python-numpy python-setuptools python-scipy libatlas-base-dev
  - sudo pip install -U scikit-learn
  - sudo pip install scikit-monaco

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test
